# Generated by Django 3.1.2 on 2021-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsentry',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
